// Generated by gencpp from file lakibeam1/Coordinates.msg
// DO NOT EDIT!


#ifndef LAKIBEAM1_MESSAGE_COORDINATES_H
#define LAKIBEAM1_MESSAGE_COORDINATES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lakibeam1
{
template <class ContainerAllocator>
struct Coordinates_
{
  typedef Coordinates_<ContainerAllocator> Type;

  Coordinates_()
    : x(0.0)
    , y(0.0)  {
    }
  Coordinates_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::lakibeam1::Coordinates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lakibeam1::Coordinates_<ContainerAllocator> const> ConstPtr;

}; // struct Coordinates_

typedef ::lakibeam1::Coordinates_<std::allocator<void> > Coordinates;

typedef boost::shared_ptr< ::lakibeam1::Coordinates > CoordinatesPtr;
typedef boost::shared_ptr< ::lakibeam1::Coordinates const> CoordinatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lakibeam1::Coordinates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lakibeam1::Coordinates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lakibeam1::Coordinates_<ContainerAllocator1> & lhs, const ::lakibeam1::Coordinates_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lakibeam1::Coordinates_<ContainerAllocator1> & lhs, const ::lakibeam1::Coordinates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lakibeam1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lakibeam1::Coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lakibeam1::Coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lakibeam1::Coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lakibeam1::Coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lakibeam1::Coordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lakibeam1::Coordinates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lakibeam1::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::lakibeam1::Coordinates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::lakibeam1::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lakibeam1/Coordinates";
  }

  static const char* value(const ::lakibeam1::Coordinates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lakibeam1::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::lakibeam1::Coordinates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lakibeam1::Coordinates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Coordinates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lakibeam1::Coordinates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lakibeam1::Coordinates_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAKIBEAM1_MESSAGE_COORDINATES_H
