// Generated by gencpp from file lakibeam1/CustomLaserScan.msg
// DO NOT EDIT!


#ifndef LAKIBEAM1_MESSAGE_CUSTOMLASERSCAN_H
#define LAKIBEAM1_MESSAGE_CUSTOMLASERSCAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lakibeam1
{
template <class ContainerAllocator>
struct CustomLaserScan_
{
  typedef CustomLaserScan_<ContainerAllocator> Type;

  CustomLaserScan_()
    : header()
    , angle_min(0.0)
    , angle_max(0.0)
    , angle_increment(0.0)
    , time_increment(0.0)
    , scan_time(0.0)
    , range_min(0.0)
    , range_max(0.0)
    , ranges()
    , intensities()
    , distances()
    , angles()
    , x_coords()
    , y_coords()  {
    }
  CustomLaserScan_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , angle_min(0.0)
    , angle_max(0.0)
    , angle_increment(0.0)
    , time_increment(0.0)
    , scan_time(0.0)
    , range_min(0.0)
    , range_max(0.0)
    , ranges(_alloc)
    , intensities(_alloc)
    , distances(_alloc)
    , angles(_alloc)
    , x_coords(_alloc)
    , y_coords(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _angle_min_type;
  _angle_min_type angle_min;

   typedef float _angle_max_type;
  _angle_max_type angle_max;

   typedef float _angle_increment_type;
  _angle_increment_type angle_increment;

   typedef float _time_increment_type;
  _time_increment_type time_increment;

   typedef float _scan_time_type;
  _scan_time_type scan_time;

   typedef float _range_min_type;
  _range_min_type range_min;

   typedef float _range_max_type;
  _range_max_type range_max;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _ranges_type;
  _ranges_type ranges;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _intensities_type;
  _intensities_type intensities;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _distances_type;
  _distances_type distances;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _angles_type;
  _angles_type angles;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _x_coords_type;
  _x_coords_type x_coords;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _y_coords_type;
  _y_coords_type y_coords;





  typedef boost::shared_ptr< ::lakibeam1::CustomLaserScan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lakibeam1::CustomLaserScan_<ContainerAllocator> const> ConstPtr;

}; // struct CustomLaserScan_

typedef ::lakibeam1::CustomLaserScan_<std::allocator<void> > CustomLaserScan;

typedef boost::shared_ptr< ::lakibeam1::CustomLaserScan > CustomLaserScanPtr;
typedef boost::shared_ptr< ::lakibeam1::CustomLaserScan const> CustomLaserScanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lakibeam1::CustomLaserScan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lakibeam1::CustomLaserScan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lakibeam1::CustomLaserScan_<ContainerAllocator1> & lhs, const ::lakibeam1::CustomLaserScan_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.angle_min == rhs.angle_min &&
    lhs.angle_max == rhs.angle_max &&
    lhs.angle_increment == rhs.angle_increment &&
    lhs.time_increment == rhs.time_increment &&
    lhs.scan_time == rhs.scan_time &&
    lhs.range_min == rhs.range_min &&
    lhs.range_max == rhs.range_max &&
    lhs.ranges == rhs.ranges &&
    lhs.intensities == rhs.intensities &&
    lhs.distances == rhs.distances &&
    lhs.angles == rhs.angles &&
    lhs.x_coords == rhs.x_coords &&
    lhs.y_coords == rhs.y_coords;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lakibeam1::CustomLaserScan_<ContainerAllocator1> & lhs, const ::lakibeam1::CustomLaserScan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lakibeam1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lakibeam1::CustomLaserScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lakibeam1::CustomLaserScan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lakibeam1::CustomLaserScan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lakibeam1::CustomLaserScan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lakibeam1::CustomLaserScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lakibeam1::CustomLaserScan_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lakibeam1::CustomLaserScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6df6ab43231c4a4d8b1333313d831354";
  }

  static const char* value(const ::lakibeam1::CustomLaserScan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6df6ab43231c4a4dULL;
  static const uint64_t static_value2 = 0x8b1333313d831354ULL;
};

template<class ContainerAllocator>
struct DataType< ::lakibeam1::CustomLaserScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lakibeam1/CustomLaserScan";
  }

  static const char* value(const ::lakibeam1::CustomLaserScan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lakibeam1::CustomLaserScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 angle_min\n"
"float32 angle_max\n"
"float32 angle_increment\n"
"float32 time_increment\n"
"float32 scan_time\n"
"float32 range_min\n"
"float32 range_max\n"
"float32[] ranges\n"
"float32[] intensities\n"
"float32[] distances\n"
"float32[] angles\n"
"float32[] x_coords\n"
"float32[] y_coords\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::lakibeam1::CustomLaserScan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lakibeam1::CustomLaserScan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.angle_min);
      stream.next(m.angle_max);
      stream.next(m.angle_increment);
      stream.next(m.time_increment);
      stream.next(m.scan_time);
      stream.next(m.range_min);
      stream.next(m.range_max);
      stream.next(m.ranges);
      stream.next(m.intensities);
      stream.next(m.distances);
      stream.next(m.angles);
      stream.next(m.x_coords);
      stream.next(m.y_coords);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomLaserScan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lakibeam1::CustomLaserScan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lakibeam1::CustomLaserScan_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angle_min: ";
    Printer<float>::stream(s, indent + "  ", v.angle_min);
    s << indent << "angle_max: ";
    Printer<float>::stream(s, indent + "  ", v.angle_max);
    s << indent << "angle_increment: ";
    Printer<float>::stream(s, indent + "  ", v.angle_increment);
    s << indent << "time_increment: ";
    Printer<float>::stream(s, indent + "  ", v.time_increment);
    s << indent << "scan_time: ";
    Printer<float>::stream(s, indent + "  ", v.scan_time);
    s << indent << "range_min: ";
    Printer<float>::stream(s, indent + "  ", v.range_min);
    s << indent << "range_max: ";
    Printer<float>::stream(s, indent + "  ", v.range_max);
    s << indent << "ranges[]" << std::endl;
    for (size_t i = 0; i < v.ranges.size(); ++i)
    {
      s << indent << "  ranges[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ranges[i]);
    }
    s << indent << "intensities[]" << std::endl;
    for (size_t i = 0; i < v.intensities.size(); ++i)
    {
      s << indent << "  intensities[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.intensities[i]);
    }
    s << indent << "distances[]" << std::endl;
    for (size_t i = 0; i < v.distances.size(); ++i)
    {
      s << indent << "  distances[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.distances[i]);
    }
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.angles[i]);
    }
    s << indent << "x_coords[]" << std::endl;
    for (size_t i = 0; i < v.x_coords.size(); ++i)
    {
      s << indent << "  x_coords[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x_coords[i]);
    }
    s << indent << "y_coords[]" << std::endl;
    for (size_t i = 0; i < v.y_coords.size(); ++i)
    {
      s << indent << "  y_coords[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y_coords[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAKIBEAM1_MESSAGE_CUSTOMLASERSCAN_H
